/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "../include/gradle-jni-template.h"

std::string gradle_jni_template::Greeter::greeting() {
    return std::string("Hello, World!");
}
