/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef GRADLE_JNI_TEMPLATE_H
#define GRADLE_JNI_TEMPLATE_H

#ifdef _WIN32
#define GRADLE_JNI_TEMPLATE_EXPORT_FUNC __declspec(dllexport)
#else
#define GRADLE_JNI_TEMPLATE_EXPORT_FUNC
#endif

#include <string>

namespace gradle_jni_template {
    class Greeter {
        public:
        std::string GRADLE_JNI_TEMPLATE_EXPORT_FUNC greeting();
    };
}

#endif
