/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_alloc_util_NativeErrno */

#ifndef _Included_com_jme3_alloc_util_NativeErrno
#define _Included_com_jme3_alloc_util_NativeErrno
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_alloc_util_NativeErrno
 * Method:    getErrorNoMemory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jme3_alloc_util_NativeErrno_getErrorNoMemory
  (JNIEnv *, jclass);

/*
 * Class:     com_jme3_alloc_util_NativeErrno
 * Method:    getErrorInvalidValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jme3_alloc_util_NativeErrno_getErrorInvalidValue
  (JNIEnv *, jclass);

/*
 * Class:     com_jme3_alloc_util_NativeErrno
 * Method:    getErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jme3_alloc_util_NativeErrno_getErrno
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
